### ISSUE TITLE
Chnaging skeleton code

### ISSUE THREAD

**Issue by Ujjwal29** [westporch/codeFrame#1]
How can I change the already built-in skeleton code according to my needs and requirements?

**Comment by westporch** [comment]
Hello. :)

# 1. Language skeleton 

Please see _~/.vim/plugin/codeFrame/Languages_ directory.
codeFrame supports bash, c, c++, html, java, markdown, perl, php, python, ruby language skeleton.
 
```
root@raspberrypi-dev> ls                                                                                                                    ~/.vim/plugin/codeFrame/Languages
bash.txt  c.txt  c++.txt  html.txt  java.txt  markdown.txt  perl.txt  php.txt  python.txt  ruby.txt
```

If you want to change C language skeleton, just edit a c.txt file and save it.
Test is very simple. type _vi test.c_

```
root@raspberrypi-dev> vi test.c                                                                                                                                          /tmp
```

You can see your customized C language skeleton.

# 2. codeFrame.vim script (main source)
[codeFrame.vim](https://github.com/westporch/codeFrame/blob/master/plugin/codeFrame.vim) is primary code.  It loads skeleton text file in  _~/.vim/plugin/codeFrame/[Languages](https://github.com/westporch/codeFrame/tree/master/Languages)_ directory. 
(i.e. _~/.vim/plugin/codeFrame/Languages/[python.txt](https://github.com/westporch/codeFrame/blob/master/Languages/python.txt)_)

If you want to make text skeleton file, Please see following (STEP 1 ~ STEP 2).

## 2-(1). STEP 1: Create a skeleton file

Create a text.txt file in  _~/.vim/plugin/codeFrame/[Languages](https://github.com/westporch/codeFrame/tree/master/Languages)_ directory. 

```
root@raspberrypi-dev> vi text.txt                                                                                                           ~/.vim/plugin/codeFrame/Language
```

Type(Subject: Date:) and save.

```
Subject:
Date: 
```

## 2-(2). STEP 2: Edit codeFrame.vim script
Our aim is detecting txt extension so that someone use a text skeleton file.
Accordingly, edit [codeFrame.vim](https://github.com/westporch/codeFrame/blob/master/plugin/codeFrame.vim) script.
It detects file extension in shell and loads corresponding extension file in _~/.vim/plugin/codeFrame/[Languages](https://github.com/westporch/codeFrame/tree/master/Languages)_ directory. 

Please open [codeFrame.vim](https://github.com/westporch/codeFrame/blob/master/plugin/codeFrame.vim) file and insert following lines which are highlighted.
Finally save it.

```diff
<..SNIP..>
    elseif file_type == "markdown"
        silent 0r !cat ~/.vim/plugin/codeFrame/Languages/markdown.txt
        call search(':---:', "b")                                                                                                                                             
        call Set_cursor_position()
+    elseif file_type == "txt"
+        silent 0r !cat ~/.vim/plugin/codeFrame/Languages/text.txt
+        call Set_cursor_position()
    endif

```

Test is simple. Just type vi deleteMe.txt

```
root@raspberrypi-dev> vi deleteMe.txt                                                                                                                                    /tmp
```

```
Subject:
Date: 
```

Thanks.

**Comment by Ujjwal29** [comment]
Hey!
I got it fixed.
Anyway, Thanks for replying.
